# Generated by Django 5.0.7 on 2024-07-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
