# Generated by Django 5.0.7 on 2024-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_added_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
