# Generated by Django 5.0.7 on 2024-07-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=70)),
                ('package_discription', models.TextField(blank=True, null=True)),
                ('price_per_head', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_banner_image', models.ImageField(upload_to='trips/banner')),
                ('package_inclusions', models.TextField()),
                ('package_exclusions', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
