# Generated by Django 5.0.7 on 2024-07-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_packageitnary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageitnary',
            old_name='dicription',
            new_name='discription',
        ),
    ]
