# Generated by Django 5.0.7 on 2024-07-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trippackage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippackage',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
