# Generated by Django 5.0.7 on 2024-07-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trippackage_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion', models.CharField(max_length=80)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion', to='trips.trippackage')),
            ],
        ),
        migrations.CreateModel(
            name='TripInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion', models.CharField(max_length=80)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion', to='trips.trippackage')),
            ],
        ),
    ]
