# Generated by Django 5.0.7 on 2024-07-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('trips', '0006_tripexclusion_tripinclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('total_participants', models.PositiveIntegerField()),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Initiated', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripbooking', to='customers.customerprofile')),
                ('trip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripbooking', to='trips.trippackage')),
            ],
        ),
    ]
