# Generated by Django 5.0.7 on 2024-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_tripbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
