# Generated by Django 5.0.7 on 2024-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_tripbooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='ending_date',
            field=models.DateField(blank=True),
        ),
    ]
