# Generated by Django 5.0.7 on 2024-07-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_tripbooking_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='ending_date',
            field=models.DateField(),
        ),
    ]
