# Generated by Django 5.0.7 on 2024-07-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_tripbooking_ending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='booker_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
