# Generated by Django 5.0.7 on 2024-08-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_tripbooking_booker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
