# Generated by Django 5.0.7 on 2024-08-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_tripbooking_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
